### ISSUE TITLE
Document element.render option for multiple props

### ISSUE THREAD

**Issue by pratapvardhan** [gramener/uifactory#3]
To re-render the element with multiple props, we could use the `.render` method?

```html
<template component="two-props" a="a" b="b">
  <%= a %><%= b %>
</template>
```

```javascript
document.querySelector('two-props').render({a: 1, b: 2})
// vs
document.querySelector('two-props').a = 1
document.querySelector('two-props').b = 2
```

or document a recommended way to update multiple props object in a single call?

**Comment by sanand0** [comment]
The `.render()` method is the recommended way to render with multiple property updates. I'll document that.

**Comment by sanand0** [comment]
Fixed via `.update()` in v0.0.5. See 29a9561
